---
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  username: <%= ENV["POSTGRESQL_USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] || 'postgres' %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: product_definition_development

test:
  <<: *default
  database: product_definition_service_test

production:
  <<: *default
